version: '3.7'

services:

#  frontend:
#    restart: always
#    container_name: frontend
#    env_file:
#      - ./frontend/.env
#    build:
#      context: ./frontend
#    ports:
#      - 8080:8080
#    expose:
#      - 8080

#  backend:
#    restart: always
#    container_name: backend
#    build:
#      context: .
#    ports:
#      - 8000:8000
#    expose:
#      - 8000
#    depends_on:
#      - db
#    command: ['uvicorn', 'fastApi.main:app', '--host=0.0.0.0', '--port=8000', '--reload']



  db:
    build:
      context: ./database
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data
