version: '3.7'

services:

#  frontend:
#    restart: always
#    container_name: frontend
#    env_file:
#      - ./frontend/.env
#    build:
#      context: ./frontend
#    ports:
#      - 8080:8080
#    expose:
#      - 8080
#
#  backend:
#    restart: always
#    container_name: backend
#    env_file:
#      - ./.env
#    build:
#      context: ./fastApi
#    ports:
#      - 8082:8082
#    expose:
#      - 8082
#    depends_on:
#      - db
#    command: ['uvicorn', 'main:app', '--host=0.0.0.0', '--port=8082', '--reload']



  db:
    build:
      context: ./database
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - ALLOW_IP_RANGE=0.0.0.0/0
    ports:
      - "5432:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data
